// Fill out your copyright notice in the Description page of Project Settings.


#include "Core/Singletons/BulletPhysicsWorldSubsystem.h"

#include "BulletDebugDrawer.h"
#include "BulletLogChannels.h"
#include "EngineUtils.h"
#include "ThirdParty/BulletPhysicsEngineLibrary/bullet3/Extras/Serialize/BulletFileLoader/autogenerated/bullet.h"

int32 DrawDebugShapes = 0;
static FAutoConsoleVariableRef CVarDisableDataCopyInPlace(
	TEXT("b.debug.draw"),
	DrawDebugShapes,
	TEXT("Show the bullet collision shapes according to the bullet world view"),
	ECVF_Default);

const FVector UE_WORLD_ORIGIN = FVector(0);

void UBulletPhysicsWorldSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
	Super::Initialize(Collection);
	
	PhysicsDeltaTime = 1/PhysicsRefreshRate;

	BtCollisionConfig = new btDefaultCollisionConfiguration();
	BtCollisionDispatcher = new btCollisionDispatcher(BtCollisionConfig);

	BtBroadphase = new btDbvtBroadphase();

	mt = new btSequentialImpulseConstraintSolver;
	mt->setRandSeed(1234);

	BtConstraintSolver = mt;
	BtWorld = new btDiscreteDynamicsWorld(BtCollisionDispatcher, BtBroadphase, BtConstraintSolver, BtCollisionConfig);
	BtWorld->setGravity(btVector3(Gravity.X,Gravity.Y, Gravity.Z));

	UE_LOG(LogTemp, Warning, TEXT("UBulletPhysicsWorldSubsystem:: Bullet world init"));

	if (GetWorld() == nullptr) {
		UE_LOG(LogTemp, Warning, TEXT("UBulletPhysicsWorldSubsystem::GetWorld() returned null"));
		return;
	}
	
}

void UBulletPhysicsWorldSubsystem::OnWorldBeginPlay(UWorld& InWorld)
{
	FName bulletStaticTag = FName("B_STATIC");
	FName bulletDynamicTag = FName("B_DYNAMIC");
	
	Super::OnWorldBeginPlay(InWorld);
	for (TActorIterator<AActor> actorItr(&InWorld); actorItr; ++actorItr)
	{
		AActor* actor = *actorItr;
		if (!actor)
			continue;

		int dummyID = 0; // Doesn't really matter
		// Check if the actor has a UStaticMeshComponent directly
		if (actor->ActorHasTag(bulletStaticTag))
		{
			RegisterStaticRigidBody(actor,0.5,0.9, false, dummyID);
		}else if (actor->ActorHasTag(bulletDynamicTag))
		{
			RegisterDynamicRigidBody(actor,0.5,0.9,5.f, false,dummyID );
		}
	}
}


void UBulletPhysicsWorldSubsystem::RegisterDynamicRigidBody(AActor* Target, float Friction, float Restitution, float Mass, bool bUsePhysicsMaterial, UPARAM(DisplayName="RigidBodyId") int32&Id )
{
	
	FUnrealShapeDescriptor Descriptor;
	ExtractPhysicsGeometry(Target,[Target, this, Friction, Restitution, &Descriptor, Mass](btCollisionShape* Shape, const FTransform& RelTransform)
	{
		// Every sub-collider in the actor is passed to this callback function
		// We're baking this in world space, so apply actor transform to relative
		const FTransform FinalXform = RelTransform;
		btVector3 Inertia;
		Shape->calculateLocalInertia(Mass, Inertia);
		if (const btCollisionObject* CollisionObject = AddRigidBody(Target, RelTransform, Shape, Inertia, Mass, Friction, Restitution))
		{
			Descriptor.WorldArrayIndex = CollisionObject->getWorldArrayIndex();
			Descriptor.ShapeOwner = Target;
			GlobalShapeDescriptorDataCache.Add(CollisionObject, Descriptor);
		}
	}, Descriptor);
	
	
	Id = Descriptor.WorldArrayIndex;
}

void UBulletPhysicsWorldSubsystem::RegisterStaticRigidBody(AActor* Target, float Friction, float Restitution, bool bUsePhysicsMaterial, UPARAM(DisplayName="RigidBodyId") int32&Id )
{
	FUnrealShapeDescriptor Descriptor;
	ExtractPhysicsGeometry(Target,[Target, this, Friction, Restitution, &Descriptor](btCollisionShape* Shape, const FTransform& RelTransform)
	{
		// Every sub-collider in the actor is passed to this callback function
		// We're baking this in world space, so apply actor transform to relative
		const FTransform FinalXform = RelTransform /** Target->GetActorTransform()*/;
		if (const btCollisionObject* CollisionObject = AddStaticCollision(Shape, FinalXform, Friction, Restitution, Target))
		{
			Descriptor.WorldArrayIndex = CollisionObject->getWorldArrayIndex();
			Descriptor.ShapeOwner = Target;
			GlobalShapeDescriptorDataCache.Add(CollisionObject, Descriptor);
		}
	}, Descriptor);
	
	
	Id = Descriptor.WorldArrayIndex;
}


btCollisionShape* UBulletPhysicsWorldSubsystem::GetBoxCollisionShape(const FVector& Dimensions)
{
	// Simple brute force lookup for now, probably doesn't need anything more clever
	btVector3 HalfSize = BulletHelpers::ToBulletVector3(Dimensions * 0.5);
	for (auto&& S : BtBoxCollisionShapes)
	{
		btVector3 Sz = S->getHalfExtentsWithMargin();
		if (FMath::IsNearlyEqual(Sz.x(), HalfSize.x()) &&
				FMath::IsNearlyEqual(Sz.y(), HalfSize.y()) &&
				FMath::IsNearlyEqual(Sz.z(), HalfSize.z()))
		{
			return S;
		}
	}

	// Not found, create
	auto S = new btBoxShape(HalfSize);
	// Get rid of margins, just cause issues for me
	S->setMargin(0);
	BtBoxCollisionShapes.Add(S);

	return S;

}

btCollisionShape* UBulletPhysicsWorldSubsystem::GetSphereCollisionShape(float Radius)
{
	// Simple brute force lookup for now, probably doesn't need anything more clever
	btScalar Rad = BulletHelpers::ToBulletFloat(Radius);
	for (auto&& S : BtSphereCollisionShapes)
	{
		// Bullet subtracts a margin from its internal shape, so add back to compare
		if (FMath::IsNearlyEqual(S->getRadius(), Rad))
		{
			return S;
		}
	}

	// Not found, create
	auto S = new btSphereShape(Rad);
	// Get rid of margins, just cause issues for me
	S->setMargin(0);
	BtSphereCollisionShapes.Add(S);

	return S;

}

btCollisionShape* UBulletPhysicsWorldSubsystem::GetCapsuleCollisionShape(float Radius, float Height)
{
	// Simple brute force lookup for now, probably doesn't need anything more clever
	btScalar R = BulletHelpers::ToBulletFloat(Radius);
	btScalar H = BulletHelpers::ToBulletFloat(Height);
	btScalar HalfH = H * 0.5f;

	for (auto&& S : BtCapsuleCollisionShapes)
	{
		// Bullet subtracts a margin from its internal shape, so add back to compare
		if (FMath::IsNearlyEqual(S->getRadius(), R) &&
				FMath::IsNearlyEqual(S->getHalfHeight(), HalfH))
		{
			return S;
		}
	}

	// Not found, create
	auto S = new btCapsuleShape(R, H);
	BtCapsuleCollisionShapes.Add(S);

	return S;

}

btBvhTriangleMeshShape* UBulletPhysicsWorldSubsystem::GetComplexShape(const FTransform& CurrentTransform, UStaticMesh* Mesh)
{
	/* Note that Mesh->ComplexCollisionMesh is WITH_EDITORONLY_DATA so not available at runtime
	   Looks like we have to access LODForCollision, RenderData->LODResources
	   So they use a mesh LOD for collision for complex shapes, never drawn usually?*/

	FStaticMeshRenderData* renderData = Mesh->GetRenderData();
	if (!renderData)
	{
		UE_LOG(LogBullet, Error, TEXT("Invalid render data. (complex collision extraction)"));
		return nullptr;
	}
	if (renderData->LODResources.Num() == 0)
	{
		UE_LOG(LogBullet, Error, TEXT("LODResources zero. (complex collision extraction)"));
		return nullptr;
	}
	
	bool bHasExistingMeshInCache = false;
	
	FStaticMeshLODResources& LODResources = renderData->LODResources[0]; //TODO@GreggoryAddison::CodeOptimization || Do NOT do this if the mesh is a nanite mesh. To be safe use the proxy mesh if possible.

	const FPositionVertexBuffer& VertexBuffer = LODResources.VertexBuffers.PositionVertexBuffer;

	const uint32 vertices = VertexBuffer.GetNumVertices();
	
	btTriangleMesh* TriangleMesh = new btTriangleMesh();
	FVector scale = CurrentTransform.GetScale3D();
	
	const FIndexArrayView Indices = LODResources.IndexBuffer.GetArrayView();
	
	//TODO:@GreggoryAddison::CodeOptimization || Check if the cache already has a shape with similar verts and scaling.
	/*for (btBvhTriangleMeshShape* CacheShape : ComplexShapes)
	{
		
	}*/
	
	/* Only supporting 1 material for the mesh for now
	 * 
	 */
	const int MaterialIDX = 0; //TODO@GreggoryAddison::CodeCompletion || To support multiple material ids I would need to find out what material id is associated with this triangle. ONLY IMPORTANT IF THIS IS RENDERED
	for (int32 i = 0; i < Indices.Num(); i += 3)
	{
		uint32 verIdx1 = Indices[i];
		uint32 verIdx2 = Indices[i + 1];
		uint32 verIdx3 = Indices[i + 2];

		// Validate indices
		if (verIdx1 >= vertices || verIdx2 >= vertices || verIdx3 >= vertices)
		{
			UE_LOG(LogBullet, Error, TEXT("Invalid triangle indices detected!"));
			continue;
		}
		const btVector3 Vert1 = BulletHelpers::ToBulletPosition(VertexBuffer.VertexPosition(verIdx1), UE_WORLD_ORIGIN);
		const btVector3 Vert2 = BulletHelpers::ToBulletPosition(VertexBuffer.VertexPosition(verIdx2), UE_WORLD_ORIGIN);
		const btVector3 Vert3 = BulletHelpers::ToBulletPosition(VertexBuffer.VertexPosition(verIdx3), UE_WORLD_ORIGIN);
		TriangleMesh->addTriangle(Vert1, Vert2, Vert3);
	}
	
	TriangleMesh->setScaling(BulletHelpers::ToBulletVector3(scale));

	if (Mesh->GetBodySetup())
	{
		//physicsMaterialList.push_back(GetJoltPhysicsMaterial(Mesh->GetBodySetup()->GetPhysMaterial()));
	}
	// TODO@GreggoryAddison::CodeCompletion || Caching mechanism for MeshShapes
	
	btBvhTriangleMeshShape* TriMesh = new btBvhTriangleMeshShape(TriangleMesh,true);
	
	ComplexShapes.Add(TriMesh);

	if (!TriMesh)
	{
		UE_LOG(LogBullet, Error, TEXT("Failed to create mesh."));
		return nullptr;
	}
	
	return TriMesh;
}

btCollisionShape* UBulletPhysicsWorldSubsystem::GetTriangleMeshShape(TArray<FVector> a, TArray<FVector> b, TArray<FVector> c, TArray<FVector> d)
{
	btTriangleMesh* triangleMesh = new btTriangleMesh();

	for (int i =0;i<a.Num();i++)
	{
		triangleMesh->addTriangle(BulletHelpers::ToBulletPosition(a[i], FVector::ZeroVector), BulletHelpers::ToBulletPosition(b[i], FVector::ZeroVector), BulletHelpers::ToBulletPosition(c[i], FVector::ZeroVector));
		triangleMesh->addTriangle(BulletHelpers::ToBulletPosition(a[i], FVector::ZeroVector), BulletHelpers::ToBulletPosition(c[i], FVector::ZeroVector), BulletHelpers::ToBulletPosition(d[i], FVector::ZeroVector));

	}
	btBvhTriangleMeshShape* Trimesh= new btBvhTriangleMeshShape(triangleMesh,true);
	return Trimesh;
}

btCollisionShape* UBulletPhysicsWorldSubsystem::GetConvexHullCollisionShape(UBodySetup* BodySetup, int ConvexIndex, const FVector& Scale)
{
	for (auto&& S : BtConvexHullCollisionShapes)
	{ 
		if (S.BodySetup == BodySetup && S.HullIndex == ConvexIndex && S.Scale.Equals(Scale))
		{
			return S.Shape;
		}
	}

	const FKConvexElem& Elem = BodySetup->AggGeom.ConvexElems[ConvexIndex];
	auto C = new btConvexHullShape();
	for (auto&& P : Elem.VertexData)
	{
		C->addPoint(BulletHelpers::ToBulletPosition(P, FVector::ZeroVector));
	}
	// Very important! Otherwise there's a gap between 
	C->setMargin(0);
	// Apparently this is good to call?
	C->initializePolyhedralFeatures();

	BtConvexHullCollisionShapes.Add({
			BodySetup,
			ConvexIndex,
			Scale,
			C
			});

	return C;
}




const UBulletPhysicsWorldSubsystem::CachedDynamicShapeData& UBulletPhysicsWorldSubsystem::GetCachedDynamicShapeData(AActor* Actor, float Mass)
{
	// We re-use compound shapes based on (leaf) BP class
	const FName ClassName = Actor->GetClass()->GetFName();



	// Because we want to support compound colliders, we need to extract all colliders first before
	// constructing the final body.
	TArray<btCollisionShape*, TInlineAllocator<20>> Shapes;
	TArray<FTransform, TInlineAllocator<20>> ShapeRelXforms;
	FUnrealShapeDescriptor Descriptor;
	ExtractPhysicsGeometry(Actor,
			[&Shapes, &ShapeRelXforms](btCollisionShape* Shape, const FTransform& RelTransform)
			{
				Shapes.Add(Shape);
				ShapeRelXforms.Add(RelTransform);
			}, Descriptor);


	CachedDynamicShapeData ShapeData;
	ShapeData.ClassName = ClassName;

	// Single shape with no transform is simplest
	if (ShapeRelXforms.Num() == 1 &&
			ShapeRelXforms[0].EqualsNoScale(FTransform::Identity))
	{
		ShapeData.Shape = Shapes[0];
		// just to make sure we don't think we have to clean it up; simple shapes are already stored
		ShapeData.bIsCompound = false;
	}
	else
	{
		// Compound or offset single shape; we will cache these by blueprint type
		btCompoundShape* CS = new btCompoundShape();
		for (int i = 0; i < Shapes.Num(); ++i)
		{
			// We don't use the actor origin when converting transform in this case since object space
			// Note that btCompoundShape doesn't free child shapes, which is fine since they're tracked separately
			CS->addChildShape(BulletHelpers::ToBulletTransform(ShapeRelXforms[i], FVector::ZeroVector), Shapes[i]);
		}

		ShapeData.Shape = CS;
		ShapeData.bIsCompound = true;
	}

	// Calculate Inertia
	ShapeData.Mass = Mass;
	ShapeData.Shape->calculateLocalInertia(Mass, ShapeData.Inertia);

	// Cache for future use
	CachedDynamicShapes.Add(ShapeData);

	return CachedDynamicShapes.Last();

}

FUnrealShapeDescriptor UBulletPhysicsWorldSubsystem::GetShapeDescriptorData(const AActor* Actor) const
{
	if (!Actor) return FUnrealShapeDescriptor();
	if (GlobalShapeDescriptorDataCache.IsEmpty()) return FUnrealShapeDescriptor();

	for (const TTuple<const btCollisionObject*, FUnrealShapeDescriptor>& Descriptor : GlobalShapeDescriptorDataCache)
	{
		if (Descriptor.Value.ShapeOwner != Actor) continue;
		return Descriptor.Value;
	}
	
	return FUnrealShapeDescriptor();
}

int32 UBulletPhysicsWorldSubsystem::GetActorRootShapeId(const AActor* Actor) const
{
	if (!Actor) return INDEX_NONE;
	if (GlobalShapeDescriptorDataCache.IsEmpty()) return INDEX_NONE;

	for (const TTuple<const btCollisionObject*, FUnrealShapeDescriptor>& Descriptor : GlobalShapeDescriptorDataCache)
	{
		if (Descriptor.Value.ShapeOwner != Actor) continue;
		return Descriptor.Value.WorldArrayIndex;
	}
	
	return INDEX_NONE;
}


btRigidBody* UBulletPhysicsWorldSubsystem::AddRigidBody(AActor* Actor, const FTransform& FinalTransform, btCollisionShape* CollisionShape, btVector3 Inertia, float Mass, float Friction, float Restitution)
{

	FBulletMotionState* MotionState = new FBulletMotionState(Actor, UE_WORLD_ORIGIN);
	const btRigidBody::btRigidBodyConstructionInfo rbInfo(Mass, MotionState, CollisionShape, Inertia);
	btRigidBody* body = new btRigidBody(rbInfo);
	body->setUserPointer(Actor);
	body->setWorldTransform(BulletHelpers::ToBulletTransform(FinalTransform, UE_WORLD_ORIGIN));
	body->setActivationState(DISABLE_DEACTIVATION);
	body->setDeactivationTime(0);
	body->setAngularFactor(btVector3(0, 0, 1));
	BtWorld->addRigidBody(body);
	BtRigidBodies.Add(body);
	return body;
}

btRigidBody* UBulletPhysicsWorldSubsystem::AddRigidBody(USkeletalMeshComponent* skel, const FTransform& PhysicsAssetTransform, btCollisionShape* collisionShape, float mass, float friction, float restitution)
{
	checkf(skel!=nullptr, TEXT("Got null skeletal mesh"));
	btVector3 inertia(0,0,0);
	checkf(collisionShape!=nullptr, TEXT("Please configure physics asset for: %s"), *skel->GetName());
	collisionShape->calculateLocalInertia(mass, inertia);
	FBulletUEMotionState* objMotionState = new FBulletUEMotionState(skel, UE_WORLD_ORIGIN, PhysicsAssetTransform);
	const btRigidBody::btRigidBodyConstructionInfo rbInfo(mass, objMotionState, collisionShape, inertia);
	btRigidBody* body = new btRigidBody(rbInfo);
	body->setUserPointer(skel->GetOwner());
	body->setActivationState(DISABLE_DEACTIVATION);
	body->setDeactivationTime(0);

	BtWorld->addRigidBody(body);
	BtRigidBodies.Add(body);
	return body;
}

void UBulletPhysicsWorldSubsystem::SetPhysicsState(int ID, FTransform transforms, FVector Velocity, FVector AngularVelocity, FVector& Force)
{

	if (BtRigidBodies[ID]) {
		BtRigidBodies[ID]->setWorldTransform(BulletHelpers::ToBulletTransform(transforms, UE_WORLD_ORIGIN));
		BtRigidBodies[ID]->setLinearVelocity(BulletHelpers::ToBulletPosition(Velocity, UE_WORLD_ORIGIN));
		BtRigidBodies[ID]->setAngularVelocity(BulletHelpers::ToBulletPosition(AngularVelocity, FVector(0)));
	}


}

void UBulletPhysicsWorldSubsystem::GetPhysicsState(int ID, FTransform& transforms, FVector& Velocity, FVector& AngularVelocity,FVector& Force)
{
	btCollisionObjectArray& CollisionObjects = GetBulletWorld()->getCollisionObjectArray();
	
	if (CollisionObjects.size()<=ID) {
		UE_LOG(LogTemp, Warning, TEXT("No Collision Object"));
		return;
	}
	
	if (!CollisionObjects[ID]) {
		UE_LOG(LogTemp, Warning, TEXT("Null Collision Object"));
		return;
	}

	if (btRigidBody* Rb = btRigidBody::upcast(CollisionObjects[ID]))
	{
		transforms= BulletHelpers::ToUnrealTransform( Rb->getWorldTransform(),UE_WORLD_ORIGIN) ;
		Velocity = BulletHelpers::ToUnrealPosition(Rb->getLinearVelocity(), UE_WORLD_ORIGIN);
		AngularVelocity = BulletHelpers::ToUnrealPosition(Rb->getAngularVelocity(), FVector(0));
		Force = BulletHelpers::ToUnrealPosition(Rb->getTotalForce(), UE_WORLD_ORIGIN);
	}
	
}

void UBulletPhysicsWorldSubsystem::GetMotionState(int Id, FTransform& Transforms, FVector& Velocity, FVector& AngularVelocity, FVector& Force)
{
	btCollisionObjectArray& CollisionObjects = GetBulletWorld()->getCollisionObjectArray();
	
	if (CollisionObjects.size()<=Id)
	{
		UE_LOG(LogBullet, Error, TEXT("No Collision Object"));
		return;
	}
	
	if (!CollisionObjects[Id]) 
	{
		UE_LOG(LogBullet, Error, TEXT("Null Collision Object"));
		return;
	}

	if (btRigidBody* Rb = btRigidBody::upcast(CollisionObjects[Id]))
	{
		if (!Rb->getMotionState()) 
		{
			UE_LOG(LogBullet, Error, TEXT("Rigid body doesn't have a valid motion state"));
			return;
		}
		
		const FBulletMotionState* MotionState = static_cast<FBulletMotionState*>(Rb->getMotionState());
		if (!MotionState) 
		{
			UE_LOG(LogBullet, Error, TEXT("Rigid body doesn't have a valid motion state"));
			return;
		}
		
		Transforms = MotionState->GetFinalTransform();
		Velocity = BulletHelpers::ToUnrealPosition(Rb->getLinearVelocity(), UE_WORLD_ORIGIN);
		AngularVelocity = BulletHelpers::ToUnrealPosition(Rb->getAngularVelocity(), FVector(0));
		Force = BulletHelpers::ToUnrealPosition(Rb->getTotalForce(), UE_WORLD_ORIGIN);
	}
	else
	{
		UE_LOG(LogBullet, Error, TEXT("ID did not point to a rigid body"));
	}
}

void UBulletPhysicsWorldSubsystem::StepPhysics(float deltaSeconds, int maxSubSteps, float fixedTimeStep)
{
	TRACE_CPUPROFILER_EVENT_SCOPE(StepPhysics);
	BtWorld->stepSimulation(deltaSeconds,maxSubSteps,fixedTimeStep);

#if WITH_EDITOR
	if (DrawDebugShapes == 1) 
	{
		StartDebugDrawer();
		BtWorld->debugDrawWorld();
	}
	else
	{
		StopDebugDrawer();
	}
#endif
}

void UBulletPhysicsWorldSubsystem::AddImpulse(AActor* Target, FVector Impulse, FVector Location)
{
	int32 Id = INDEX_NONE;
	const FUnrealShapeDescriptor& Descriptor = GetShapeDescriptorData(Target);
	Id = Descriptor.WorldArrayIndex;
	
	if (Id == INDEX_NONE) return;
	
	btCollisionObject* C = GetBulletWorld()->getCollisionObjectArray()[Id];
	btRigidBody* Rb = btRigidBody::upcast(C);
	if (!Rb) return;
	Rb->applyCentralImpulse(BulletHelpers::ToBulletDirection(Impulse, true));
}

void UBulletPhysicsWorldSubsystem::AddForce(AActor* Target, FVector Force, FVector Location)
{
	int32 Id = INDEX_NONE;
	const FUnrealShapeDescriptor& Descriptor = GetShapeDescriptorData(Target);
	Id = Descriptor.WorldArrayIndex;
	
	if (Id == INDEX_NONE) return;
	
	btCollisionObject* C = GetBulletWorld()->getCollisionObjectArray()[Id];
	btRigidBody* Rb = btRigidBody::upcast(C);
	if (!Rb) return;
	Rb->applyCentralForce(BulletHelpers::ToBulletDirection(Force, true));
	Rb->setAngularVelocity(btVector3(0, 0, 0));
}

void UBulletPhysicsWorldSubsystem::StartDebugDrawer()
{
	if (BtDebugDraw != nullptr) return;
	BtDebugDraw = new BulletDebugDraw(GetWorld(), UE_WORLD_ORIGIN);
	BtWorld->setDebugDrawer(BtDebugDraw);
}

void UBulletPhysicsWorldSubsystem::StopDebugDrawer()
{
	if (!BtDebugDraw) return;
	BtWorld->setDebugDrawer(nullptr);
	delete BtDebugDraw;
}

FHitResult UBulletPhysicsWorldSubsystem::LineTraceSingleByChannel(const FVector Start, const FVector End, const TEnumAsByte<ECollisionChannel> Channel, int32& HitBodyId)
{
	FHitResult Hit(-1);
	HitBodyId = LineTraceSingle(Start, End, Channel, Hit);
	
	return Hit;
}

FHitResult UBulletPhysicsWorldSubsystem::SweepSphereSingleByChannel(const float Radius, const FVector Start, const FVector End, 
	const TEnumAsByte<ECollisionChannel> Channel, int32& HitBodyId)
{
	FHitResult Hit(-1);

	const FCollisionShape Shape = FCollisionShape::MakeSphere(Radius);
	HitBodyId = SweepTraceSingle(Shape, Start, End, Channel, Hit);
	
	return Hit;
}

FHitResult UBulletPhysicsWorldSubsystem::SweepCapsuleSingleByChannel(const float Radius, const float HalfHeight,
	const FVector Start, const FVector End, const TEnumAsByte<ECollisionChannel> Channel, int32& HitBodyId)
{
	FHitResult Hit(-1);

	const FCollisionShape Shape = FCollisionShape::MakeCapsule(Radius, HalfHeight);
	HitBodyId = SweepTraceSingle(Shape, Start, End, Channel, Hit);
	
	return Hit;
}

FHitResult UBulletPhysicsWorldSubsystem::SweepBoxSingleByChannel(const FVector BoxExtents, const FVector Start, const FVector End, const TEnumAsByte<ECollisionChannel> Channel, int32& HitBodyId)
{
	FHitResult Hit(-1);

	const FCollisionShape Shape = FCollisionShape::MakeBox(BoxExtents);
	HitBodyId = SweepTraceSingle(Shape, Start, End, Channel, Hit);
	
	return Hit;
}

int32 UBulletPhysicsWorldSubsystem::LineTraceSingle(const FVector Start, const FVector End, const TEnumAsByte<ECollisionChannel> Channel, FHitResult& OutHit)
{
	if (!BtWorld) {
		UE_LOG(LogTemp, Warning, TEXT("UBulletSubsystem::RayTestSingle: loaded wihout a bullet world't work"));
		return INDEX_NONE;
	} 

	
	btVector3 fromV = BulletHelpers::ToBulletPosition(Start, FVector(0));
	btVector3 toV = BulletHelpers::ToBulletPosition(End, FVector(0));
	btCollisionWorld::ClosestRayResultCallback rayCallback(fromV, toV);

	btTransform fromTransform, toTransform;
	fromTransform.setIdentity();
	fromTransform.setOrigin(fromV);

	toTransform.setIdentity();
	toTransform.setOrigin(toV);

	// TODO:@GreggoryAddison::CodeCompletion || This will need to loop over all objects in the world that are apart of the passed in collision channel. Will have to filter by distance to get closest hit.
	BtWorld->rayTestSingle(
			fromTransform,
			toTransform,
			GetStaticObject(0) ,
			GetStaticObject(0)->getCollisionShape(),
			GetStaticObject(0)->getWorldTransform(),
			rayCallback
			);
	
	ConstructHitResult(rayCallback, OutHit);
	
	return rayCallback.hasHit() ? rayCallback.m_collisionObject->getWorldArrayIndex() : INDEX_NONE;
}

int32 UBulletPhysicsWorldSubsystem::SweepTraceSingle(const FCollisionShape& Shape, const FVector& Start, const FVector& End, 
	const TEnumAsByte<ECollisionChannel>& Channel, FHitResult& OutHit)
{
	if (!BtWorld) {
		UE_LOG(LogTemp, Warning, TEXT("UBulletSubsystem::RayTestSingle: loaded wihout a bullet world't work"));
		return INDEX_NONE;
	} 
	
	const btCollisionShape* CollisionShape = nullptr;

	if (Shape.IsBox())
	{
		CollisionShape = GetBoxCollisionShape(Shape.GetBox());
	}
	else if (Shape.IsSphere())
	{
		CollisionShape = GetSphereCollisionShape(Shape.GetSphereRadius());
	}
	else if (Shape.IsCapsule())
	{
		CollisionShape = GetCapsuleCollisionShape(Shape.GetCapsuleRadius(), Shape.GetCapsuleHalfHeight());
	}

	
	btVector3 fromV = BulletHelpers::ToBulletPosition(Start, FVector(0));
	btVector3 toV = BulletHelpers::ToBulletPosition(End, FVector(0));
	btCollisionWorld::ClosestConvexResultCallback rayCallback(fromV, toV);

	btTransform fromTransform, toTransform;
	fromTransform.setIdentity();
	fromTransform.setOrigin(fromV);

	toTransform.setIdentity();
	toTransform.setOrigin(toV);

	// TODO:@GreggoryAddison::CodeCompletion || This will need to loop over all objects in the world that are apart of the passed in collision channel. Will have to filter by distance to get closest hit.
	BtWorld->convexSweepTest(
			(btConvexShape*)CollisionShape,
			fromTransform,
			toTransform,
			rayCallback
			);
	
	ConstructHitResult(rayCallback, OutHit);
	
	return rayCallback.hasHit() ? rayCallback.m_hitCollisionObject->getWorldArrayIndex() : INDEX_NONE;
}

int32 UBulletPhysicsWorldSubsystem::SweepTraceSingle(const FCollisionShape& Shape, const FTransform& Start, const FTransform& End, const TEnumAsByte<ECollisionChannel>& Channel, FHitResult& OutHit)
{
	if (!BtWorld) {
		UE_LOG(LogTemp, Warning, TEXT("UBulletSubsystem::RayTestSingle: loaded wihout a bullet world't work"));
		return INDEX_NONE;
	} 
	
	const btCollisionShape* CollisionShape = nullptr;

	if (Shape.IsBox())
	{
		CollisionShape = GetBoxCollisionShape(Shape.GetBox());
	}
	else if (Shape.IsSphere())
	{
		CollisionShape = GetSphereCollisionShape(Shape.GetSphereRadius());
	}
	else if (Shape.IsCapsule())
	{
		CollisionShape = GetCapsuleCollisionShape(Shape.GetCapsuleRadius(), Shape.GetCapsuleHalfHeight());
	}

	
	btVector3 fromV = BulletHelpers::ToBulletPosition(Start.GetLocation(), FVector(0));
	btVector3 toV = BulletHelpers::ToBulletPosition(End.GetLocation(), FVector(0));
	btCollisionWorld::ClosestConvexResultCallback rayCallback(fromV, toV);

	btTransform toTransform = BulletHelpers::ToBulletTransform(End, UE_WORLD_ORIGIN);
	btTransform fromTransform = BulletHelpers::ToBulletTransform(Start, UE_WORLD_ORIGIN);
	
	// TODO:@GreggoryAddison::CodeCompletion || This will need to loop over all objects in the world that are apart of the passed in collision channel. Will have to filter by distance to get closest hit.
	BtWorld->convexSweepTest(
			(btConvexShape*)CollisionShape,
			fromTransform,
			toTransform,
			rayCallback
			);
	
	ConstructHitResult(rayCallback, OutHit);
	
	return rayCallback.hasHit() ? rayCallback.m_hitCollisionObject->getWorldArrayIndex() : INDEX_NONE;
}

void UBulletPhysicsWorldSubsystem::ConstructHitResult(const btCollisionWorld::ClosestRayResultCallback& Result, FHitResult& OutHit) const
{
	UPhysicalMaterial* UEMat = nullptr;

	const FVector HitLocation = BulletHelpers::ToUnrealPosition(Result.m_hitPointWorld, UE_WORLD_ORIGIN);
	const FVector ImpactNormal = BulletHelpers::ToUnrealDirection(Result.m_hitNormalWorld);
	
	OutHit.bBlockingHit = Result.hasHit();
	OutHit.Location = HitLocation;
	OutHit.ImpactPoint = HitLocation;
	OutHit.ImpactNormal = ImpactNormal;
	OutHit.Normal = ImpactNormal;
	if (GlobalShapeDescriptorDataCache.Contains(Result.m_collisionObject))
	{
		const FUnrealShapeDescriptor& Data = GlobalShapeDescriptorDataCache[Result.m_collisionObject];
		UPrimitiveComponent* HitComp = Data.FindClosestPrimitive(HitLocation);
		OutHit.Component = HitComp;
		OutHit.HitObjectHandle = FActorInstanceHandle(Data.ShapeOwner.Get());

		if (const UStaticMeshComponent* S = Cast<UStaticMeshComponent>(HitComp))
		{
			if (S->GetMaterials().Num() == 0) return;
			OutHit.PhysMaterial = S->GetMaterial(0)->GetPhysicalMaterial();
		}
	}

}

void UBulletPhysicsWorldSubsystem::ConstructHitResult(const btCollisionWorld::ClosestConvexResultCallback& Result, FHitResult& OutHit) const
{
	UPhysicalMaterial* UEMat = nullptr;

	const FVector HitLocation = BulletHelpers::ToUnrealPosition(Result.m_hitPointWorld, UE_WORLD_ORIGIN);
	const FVector ImpactNormal = BulletHelpers::ToUnrealDirection(Result.m_hitNormalWorld);
	
	OutHit.bBlockingHit = Result.hasHit();
	OutHit.Location = HitLocation;
	OutHit.ImpactPoint = HitLocation;
	OutHit.ImpactNormal = ImpactNormal;
	OutHit.Normal = ImpactNormal;
	if (GlobalShapeDescriptorDataCache.Contains(Result.m_hitCollisionObject))
	{
		const FUnrealShapeDescriptor& Data = GlobalShapeDescriptorDataCache[Result.m_hitCollisionObject];
		UPrimitiveComponent* HitComp = Data.FindClosestPrimitive(HitLocation);
		OutHit.Component = HitComp;
		OutHit.HitObjectHandle = FActorInstanceHandle(Data.ShapeOwner.Get());

		if (const UStaticMeshComponent* S = Cast<UStaticMeshComponent>(HitComp))
		{
			if (S->GetMaterials().Num() == 0) return;
			OutHit.PhysMaterial = S->GetMaterial(0)->GetPhysicalMaterial();
		}
	}
}


btCollisionObject* UBulletPhysicsWorldSubsystem::GetStaticObject(int ID)
{
	return BtStaticObjects[ID];
}


void UBulletPhysicsWorldSubsystem::SetupStaticGeometryPhysics(TArray<AActor*> Actors, float Friction, float Restitution)
{
	for (AActor* Actor : Actors)
	{
		FUnrealShapeDescriptor Descriptor;
		ExtractPhysicsGeometry(Actor,[Actor, this, Friction, Restitution, &Descriptor](btCollisionShape* Shape, const FTransform& RelTransform)
		{
			// Every sub-collider in the actor is passed to this callback function
			// We're baking this in world space, so apply actor transform to relative
			const FTransform FinalXform = RelTransform * Actor->GetActorTransform();
			if (const btCollisionObject* CollisionObject = AddStaticCollision(Shape, FinalXform, Friction, Restitution, Actor))
			{
				Descriptor.WorldArrayIndex = CollisionObject->getWorldArrayIndex();
				Descriptor.ShapeOwner = Actor;
				GlobalShapeDescriptorDataCache.Add(CollisionObject, Descriptor);
			}
		}, Descriptor);
	}
}

void UBulletPhysicsWorldSubsystem::ExtractPhysicsGeometry(AActor* Actor, PhysicsGeometryCallback CB, FUnrealShapeDescriptor& ShapeDescriptor)
{
	TInlineComponentArray<UPrimitiveComponent*, 20> Components;
	// Used to easily get a component's transform relative to actor, not parent component
	const FTransform InvActorTransform = Actor->GetActorTransform();

	// Collisions from meshes
	Actor->GetComponents(UPrimitiveComponent::StaticClass(), Components);
	for (UPrimitiveComponent* Comp : Components)
	{
		ShapeDescriptor.Add(Comp);
		
		if (Cast<UStaticMeshComponent>(Comp))
		{
			ExtractPhysicsGeometry(Cast<UStaticMeshComponent>(Comp), InvActorTransform, CB, ShapeDescriptor);
		}
		else if (Cast<UShapeComponent>(Comp))
		{
			ExtractPhysicsGeometry(Cast<UShapeComponent>(Comp), InvActorTransform, CB, ShapeDescriptor);
		}
	}
}

btCollisionObject* UBulletPhysicsWorldSubsystem::AddStaticCollision(btCollisionShape* Shape, const FTransform& Transform, float Friction, float Restitution, AActor* Actor)
{
	if (!BtWorld){
		UE_LOG(LogTemp, Warning, TEXT("UBulletPhysicsWorldSubsystem::AddStaticCollision: BtWorld is empty"));
		return nullptr;
	}
	btTransform Xform = BulletHelpers::ToBulletTransform(Transform, UE_WORLD_ORIGIN);
	btCollisionObject* Obj = new btCollisionObject();
	Obj->setCollisionShape(Shape);
	Obj->setWorldTransform(Xform);
	Obj->setFriction(Friction);
	Obj->setRestitution(Restitution);
	Obj->setUserPointer(Actor);
	Obj->setActivationState(DISABLE_DEACTIVATION);
	BtWorld->addCollisionObject(Obj);
	BtStaticObjects.Add(Obj);
	return Obj;
}

void UBulletPhysicsWorldSubsystem::ExtractComplexPhysicsGeometry(const FTransform& XformSoFar, UStaticMesh* Mesh,
	PhysicsGeometryCallback Callback, FUnrealShapeDescriptor& ShapeDescriptor)
{
	btBvhTriangleMeshShape* TriMesh = GetComplexShape(XformSoFar, Mesh);
	Callback(TriMesh, XformSoFar);
}

void UBulletPhysicsWorldSubsystem::ExtractPhysicsGeometry(UStaticMeshComponent* SMC, const FTransform& InvActorXform, PhysicsGeometryCallback CB, FUnrealShapeDescriptor& ShapeDescriptor)
{
	if (!SMC) return;
	UStaticMesh* Mesh = SMC->GetStaticMesh();
	if (!Mesh) return;

	const FTransform CompTransform = SMC->GetComponentTransform();
	switch (Mesh->GetBodySetup()->CollisionTraceFlag)
	{

	case ECollisionTraceFlag::CTF_UseComplexAsSimple:
		{
			if (SMC->Mobility != EComponentMobility::Type::Movable)
			{
				// complex geo should not move.
				ExtractComplexPhysicsGeometry(CompTransform, Mesh, CB, ShapeDescriptor);
			}
			else
			{
				ExtractPhysicsGeometry(CompTransform, Mesh->GetBodySetup(), CB, ShapeDescriptor);
			}
			break;
		}
	case ECollisionTraceFlag::CTF_UseDefault:
		{
			ExtractPhysicsGeometry(CompTransform, Mesh->GetBodySetup(), CB, ShapeDescriptor);
			break;
		}
	default:
		
		break;
	}

}


void UBulletPhysicsWorldSubsystem::ExtractPhysicsGeometry(UShapeComponent* Sc, const FTransform& InvActorXform, PhysicsGeometryCallback CB, FUnrealShapeDescriptor& ShapeDescriptor)
{
	// We want the complete transform from actor to this component, not just relative to parent
	FTransform CompFullRelXForm = Sc->GetComponentTransform();
	ExtractPhysicsGeometry(CompFullRelXForm, Sc->ShapeBodySetup, CB, ShapeDescriptor);
}


void UBulletPhysicsWorldSubsystem::ExtractPhysicsGeometry(const FTransform& XformSoFar, UBodySetup* BodySetup, PhysicsGeometryCallback CB, FUnrealShapeDescriptor& ShapeDescriptor)
{
	if (!ensure(BodySetup != nullptr))
	{
		return;
	}
	
	FVector Scale = XformSoFar.GetScale3D();
	btCollisionShape* Shape = nullptr;
	btCompoundShape* CompoundShape = nullptr;
	
	//  if the total makes up more than 1, we have a compound shape configured in USkeletalMeshComponent
	if (BodySetup->AggGeom.BoxElems.Num() + BodySetup->AggGeom.SphereElems.Num() + BodySetup->AggGeom.SphylElems.Num() > 1)
	{	
		const int TotalShapes = BodySetup->AggGeom.BoxElems.Num() + BodySetup->AggGeom.SphereElems.Num() + BodySetup->AggGeom.SphylElems.Num();
		CompoundShape = new btCompoundShape(true, TotalShapes);
	}

	// Iterate over the simple collision shapes
	for (auto&& Box : BodySetup->AggGeom.BoxElems)
	{
		FVector Dimensions = FVector(Box.X, Box.Y, Box.Z) * Scale;
		// We'll re-use based on just the LxWxH, including actor scale
		// Rotation and center will be baked in world space
		UE_LOG(LogTemp, Warning, TEXT("UBulletPhysicsWorldSubsystem:: creating box"));
        Shape = GetBoxCollisionShape(Dimensions);
		FTransform ShapeXform(Box.Rotation, Box.Center);
		// Shape transform adds to any relative transform already here
		FTransform XForm = ShapeXform * XformSoFar;
		if (CompoundShape)
		{
			CompoundShape->addChildShape(BulletHelpers::ToBulletTransform(XForm, UE_WORLD_ORIGIN), Shape);
			continue;
		}
		
		
		CB(Shape, XForm);
	}
	for (auto&& Sphere : BodySetup->AggGeom.SphereElems)
	{
		// Only support uniform scale so use X
		Shape = GetSphereCollisionShape(Sphere.Radius * Scale.X);
		FTransform ShapeXform(FRotator::ZeroRotator, Sphere.Center);
		// Shape transform adds to any relative transform already here
		FTransform XForm = ShapeXform * XformSoFar;
		if (CompoundShape)
		{
			CompoundShape->addChildShape(BulletHelpers::ToBulletTransform(XForm, UE_WORLD_ORIGIN), Shape);
			continue;
		}
		CB(Shape, XForm);
	}
	// Sphyl == Capsule (??)
	for (auto&& Capsule : BodySetup->AggGeom.SphylElems)
	{
		// X scales radius, Z scales height
		Shape = GetCapsuleCollisionShape(Capsule.Radius * Scale.X, Capsule.Length * Scale.Z);
		// Capsules are in Z in UE, in Y in Bullet, so roll -90
		FRotator Rot(0, 0, -90);
		// Also apply any local rotation
		Rot += Capsule.Rotation;
		FTransform ShapeXform(Rot, Capsule.Center);
		// Shape transform adds to any relative transform already here
		FTransform XForm = ShapeXform * XformSoFar;
		
		if (CompoundShape)
		{
			CompoundShape->addChildShape(BulletHelpers::ToBulletTransform(XForm, UE_WORLD_ORIGIN), Shape);
			continue;
		}
		
		CB(Shape, XForm);
	}
	for (uint16 i = 0; const FKConvexElem& ConVexElem : BodySetup->AggGeom.ConvexElems)
	{
		Shape = GetConvexHullCollisionShape(BodySetup, i, Scale);
		i++;
		if (CompoundShape)
		{
			FTransform XForm(ConVexElem.GetTransform());
			CompoundShape->addChildShape(BulletHelpers::ToBulletTransform(XForm, UE_WORLD_ORIGIN), Shape);
			continue;
		}
		
		CB(Shape, XformSoFar);
	}

	if (CompoundShape)
	{
		Shape = CompoundShape;
		CB(Shape, XformSoFar);
		delete CompoundShape;
	}

}




